version: "alpine"
services:
#  nginx-proxy-manager:
#    image: jlesage/nginx-proxy-manager
#    ports:
#      - '18181:8181'
#      - '18080:8080'
#      - '4443:4443'
#    extra_hosts:
#      - "corsa.local:127.0.0.1"
#    depends_on:
#      - frontend
#      - backend
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend            
  frontend:
    image: cruizba/http-server
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/public
  backend:
    build: ./backend/.
    ports:
      - "8081:8081"
  whoami:
    image: containous/whoami
    command:
      # It tells whoami to start listening on 8082 instead of 80
      - --port=8082
    expose:
      - "8082"
  backend-client:
    build: ./backend-client/.
    volumes:
      - ./certs/rootCA.pem:/etc/ssl/certs/backendCA.pem
    depends_on:
      - nginx-proxy
    ports:
      - "8083:80"
    expose:
      - "8083"         