version: '3.3'
services:
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        ports:
            - '81:8181'
            - '80:8080'
            - '443:4443'
        image: jlesage/nginx-proxy-manager