apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: try-cors-proxy-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: try-cors-proxy
            port:
              number: 443          
  ingressClassName: nginx
